### ISSUE TITLE
solve isort black conflict in pre-commit 

### ISSUE THREAD

**Issue by arno1190** [gjeusel/soft-cookiecutter#1]
update pre-commit conf with this : 

```
- repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
```
